"use client";
import {useEffect,useMemo,useState} from "react";
type Sex="Female"|"Male"|"Prefer not to say"; type Level="Beginner"|"Intermediate"|"Advanced";
const moves=[
 {name:"Incline push-up",focus:"Chest · arms",base:35,pose:"push",cue:"Body in one long line",detail:"Hands just wider than shoulders. Lower with control, then press the surface away."},
 {name:"Bodyweight squat",focus:"Legs · hips",base:40,pose:"squat",cue:"Knees track over toes",detail:"Sit your hips back and down. Keep your whole foot grounded and chest comfortably tall."},
 {name:"Forearm plank",focus:"Core · shoulders",base:30,pose:"plank",cue:"Brace, breathe, stay long",detail:"Stack elbows under shoulders. Squeeze glutes gently and keep your neck neutral."},
 {name:"Glute bridge",focus:"Glutes · hamstrings",base:40,pose:"bridge",cue:"Lift from the hips",detail:"Press through your heels. Pause at the top without arching your lower back."},
 {name:"Dead bug",focus:"Core control",base:35,pose:"deadbug",cue:"Lower back stays heavy",detail:"Move the opposite arm and leg slowly. Exhale as they reach away from your centre."},
 {name:"Prone swimmer",focus:"Back · posture",base:30,pose:"swimmer",cue:"Reach long, not high",detail:"Keep your gaze down. Sweep the arms slowly while your ribs stay connected to the floor."}
];
const ages=["13–17","18–29","30–44","45–59","60+"];
function duration(base:number,age:string,sex:Sex,level:Level){const a:Record<string,number>={"13–17":.85,"18–29":1,"30–44":.95,"45–59":.85,"60+":.7},s:Record<Sex,number>={Female:.95,Male:1,"Prefer not to say":.98},l:Record<Level,number>={Beginner:.82,Intermediate:1,Advanced:1.18};return Math.max(20,Math.round(base*a[age]*s[sex]*l[level]/5)*5)}
function Figure({pose,small=false}:{pose:string;small?:boolean}){return <div className={`figure ${pose} ${small?"small":""}`} aria-hidden="true"><i className="head"/><i className="torso"/><i className="limb arm-a"/><i className="limb arm-b"/><i className="limb leg-a"/><i className="limb leg-b"/><i className="ground"/></div>}
export default function Home(){
 const[age,setAge]=useState("30–44"),[sex,setSex]=useState<Sex>("Female"),[level,setLevel]=useState<Level>("Beginner");
 const[profile,setProfile]=useState(false),[session,setSession]=useState(false),[running,setRunning]=useState(false),[active,setActive]=useState(0),[left,setLeft]=useState(0),[tab,setTab]=useState("Today");
 const plan=useMemo(()=>moves.map(x=>({...x,seconds:duration(x.base,age,sex,level)})),[age,sex,level]),minutes=Math.round((plan.reduce((n,x)=>n+x.seconds,0)*3+300)/60),current=plan[active];
 useEffect(()=>{if(!running||left<=0)return;const t=window.setInterval(()=>setLeft(v=>v-1),1000);return()=>clearInterval(t)},[running,left]);
 useEffect(()=>{if(session)setLeft(current.seconds)},[active,current.seconds,session]);
 function start(){setActive(0);setLeft(plan[0].seconds);setRunning(true);setSession(true)} function next(){if(active===5){setSession(false);setRunning(false)}else{setActive(v=>v+1);setRunning(true)}}
 return <main className="app-shell">
  <header className="topbar"><button className="brand" onClick={()=>setTab("Today")}><b>B</b>BODYWISE</button><button className="profile-pill" onClick={()=>setProfile(true)}><span>{age}</span><b>{sex==="Female"?"F":sex==="Male"?"M":"—"}</b></button></header>
  <section className="intro"><p className="eyebrow">SATURDAY · SESSION 2 OF 4</p><h1>Move well.<br/><em>Get stronger.</em></h1><p>Your plan meets you where you are, with timing tuned to your profile and progress.</p></section>
  <section className="week">{[{d:"M",n:13,x:1},{d:"T",n:14},{d:"W",n:15,x:1},{d:"T",n:16},{d:"F",n:17},{d:"S",n:18,a:1},{d:"S",n:19}].map(d=><div className={d.a?"active":""} key={d.d+d.n}><span>{d.d}</span><b>{d.n}</b>{d.x&&<i>✓</i>}</div>)}</section>
  <section className="workout"><div className="workout-copy"><span className="tag">TODAY’S PRACTICE</span><h2>Full-body<br/>foundation</h2><p>Controlled strength with a calm, steady pace.</p><div className="stats"><span><b>{minutes}</b> min</span><span><b>6</b> moves</span><span><b>3</b> rounds</span></div></div><div className="hero-figure"><Figure pose="squat"/></div><button className="start" onClick={start}>Start practice <b>→</b></button></section>
  <section className="section-head"><div><p className="eyebrow">YOUR MOVEMENTS</p><h2>Today’s positions</h2></div><span>6 total</span></section>
  <section className="exercise-list">{plan.map((x,i)=><article className="exercise" key={x.name}><small>0{i+1}</small><div className="exercise-visual"><Figure pose={x.pose} small/></div><div><h3>{x.name}</h3><p>{x.focus}</p><span>{x.cue}</span></div><aside><b>{x.seconds}</b><small>SEC</small></aside></article>)}</section>
  <section className="adapt"><b>◎</b><div><h3>Built around you</h3><p>Work intervals and recovery adjust to your age range, sex, and experience. Treat them as a starting point—move pain-free and rest whenever needed.</p><button onClick={()=>setProfile(true)}>Adjust plan</button></div></section>
  <nav className="bottom-nav">{[["●","Today"],["▤","Explore"],["◔","Progress"]].map(x=><button className={tab===x[1]?"selected":""} onClick={()=>setTab(x[1])} key={x[1]}><span>{x[0]}</span>{x[1]}</button>)}</nav>
  {profile&&<div className="overlay" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setProfile(false)} aria-label="Close"/><section className="sheet"><i/><button className="close" onClick={()=>setProfile(false)}>×</button><p className="eyebrow">PERSONALISE YOUR START</p><h2>Make the plan yours.</h2><p className="note">These settings tune the suggested work time. You can always pause, shorten, or skip a movement.</p><fieldset><legend>Age range</legend><div className="choices ages">{ages.map(x=><button className={age===x?"chosen":""} onClick={()=>setAge(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Sex</legend><div className="choices">{(["Female","Male","Prefer not to say"] as Sex[]).map(x=><button className={sex===x?"chosen":""} onClick={()=>setSex(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Experience</legend><div className="choices">{(["Beginner","Intermediate","Advanced"] as Level[]).map(x=><button className={level===x?"chosen":""} onClick={()=>setLevel(x)} key={x}>{x}</button>)}</div></fieldset><div className="preview"><span>Updated practice</span><b>{minutes} min · {plan[0].seconds} sec opening set</b></div><button className="save" onClick={()=>setProfile(false)}>Save my plan</button></section></div>}
  {session&&<section className="session" role="dialog" aria-modal="true"><header><button onClick={()=>{setSession(false);setRunning(false)}}>×</button><span>MOVE {active+1} OF 6</span><button>◒</button></header><div className="session-title"><p>{current.focus}</p><h2>{current.name}</h2></div><div className="session-visual"><Figure pose={current.pose}/></div><div className="cue"><span>FORM CUE</span><b>{current.cue}</b><p>{current.detail}</p></div><div className="timer-row"><div className="timer" style={{background:`conic-gradient(#e8ff48 ${(current.seconds-left)/current.seconds*100}%,#2e302a 0)`}}><div><b>{left}</b><span>SECONDS</span></div></div><button onClick={()=>setRunning(v=>!v)}>{running?"Ⅱ":"▶"}<span>{running?"Pause":"Resume"}</span></button><button className="next" onClick={next}>→<span>{active===5?"Finish":"Next"}</span></button></div><div className="session-progress"><i style={{width:`${(active+1)/6*100}%`}}/></div></section>}
 </main>
}
