"use client";
import {useEffect,useMemo,useState} from "react";
type Sex="Female"|"Male"|"Prefer not to say"; type Level="Beginner"|"Intermediate"|"Advanced"; type Readiness="Recover"|"Ready"|"Push"; type Tab="Today"|"Plan"|"Community"|"Progress";
type Move={name:string;focus:string;family:string;intensity:"Low"|"Medium"|"High";base:number;image:string;video:string;credit?:string;cue:string;detail:string;variants:string[];why:string};
const M:Record<string,Move>={
 push:{name:"Incline push-up",focus:"Chest · arms",family:"Push strength",intensity:"Medium",base:35,image:"/pushup-real.jpg",video:"/pushup-loop.mp4",cue:"Body in one long line",detail:"Hands just wider than shoulders. Lower with control, then press away.",variants:["Wall push-up","Incline push-up","Slow negative push-up","Full push-up prep"],why:"Builds pressing strength without jumping or equipment."},
 squat:{name:"Bodyweight squat",focus:"Quads · glutes",family:"Knee + hip pattern",intensity:"Medium",base:40,image:"/squat-real.jpg",video:"/squat-loop.mp4",cue:"Knees track over toes",detail:"Sit hips back and down. Keep your whole foot grounded and chest tall.",variants:["Sit-to-stand","Tempo squat","Squat pulse","Squat-to-reach"],why:"The base pattern for knees, hips, stairs and daily strength."},
 plank:{name:"Forearm plank",focus:"Deep core · shoulders",family:"Anti-extension core",intensity:"Medium",base:30,image:"/plank-real.jpg",video:"/plank-loop.mp4",cue:"Brace, breathe, stay long",detail:"Stack elbows under shoulders and keep your neck neutral.",variants:["Knee plank","Forearm plank","Long-lever plank","Plank shoulder tap prep"],why:"Trains the trunk to resist arching and protect the lower back."},
 bridge:{name:"Glute bridge",focus:"Glutes · hamstrings",family:"Posterior chain",intensity:"Low",base:40,image:"/bridge-real.jpg",video:"/bridge-loop.mp4",cue:"Lift from the hips",detail:"Press through heels. Pause at the top without arching your lower back.",variants:["Glute bridge hold","Marching bridge","Single-leg bridge prep","Long bridge"],why:"Wakes up glutes and hamstrings for knee and back support."},
 calfRaise:{name:"Standing calf raise",focus:"Calves · ankle support",family:"Ankle + balance",intensity:"Low",base:35,image:"/calf-raise-real.jpg",video:"https://wger.de/media/exercise-video/622/35b7b625-77fd-4c09-8c57-3ad0f2f23175.MOV",credit:"WGER · real-person demo",cue:"Rise tall, lower slowly",detail:"Use support if needed and keep weight even across both feet.",variants:["Supported calf raise","Slow eccentric calf raise","Single-leg calf prep","Calf raise balance hold"],why:"Strengthens ankles and lower-leg support for walking, stairs and knee confidence."},
 deadbug:{name:"Dead bug",focus:"Deep core control",family:"Coordination core",intensity:"Low",base:35,image:"/dead-bug-real.jpg",video:"/dead-bug-real.mp4",credit:"Cureus open-access supplement · CC BY",cue:"Lower back stays heavy",detail:"Move opposite arm and leg slowly. Exhale as they reach away.",variants:["Heel taps","Dead bug","Dead bug pause","Long-lever dead bug"],why:"Excellent beginner-safe core control without neck strain."},
 birdDog:{name:"Bird dog",focus:"Core · back control",family:"Back + trunk stability",intensity:"Low",base:35,image:"/bird-dog-real.jpg",video:"/bird-dog-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Reach without twisting",detail:"Extend opposite arm and leg while keeping hips level.",variants:["Three-point hold","Bird dog","Bird dog elbow-to-knee","Slow bird dog hover"],why:"Balances core training with back-side stability and posture work."},
 sidePlank:{name:"Side plank",focus:"Obliques · waist",family:"Side-core strength",intensity:"Medium",base:25,image:"/side-plank-real.jpg",video:"/side-plank-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Lift the underside waist",detail:"Stack shoulder over elbow and keep your body long.",variants:["Short side plank","Side plank hold","Side plank reach","Star plank prep"],why:"Targets obliques and lateral hip control that front planks miss."}
};
const goals={
 "Full body":{icon:"◎",title:"Full-body foundation",desc:"Balanced strength from head to toe.",promise:"A complete baseline that never hammers one area too hard.",rotations:[["push","squat","plank","bridge","deadbug","birdDog","calfRaise"],["squat","push","sidePlank","bridge","calfRaise","deadbug"],["plank","squat","birdDog","push","bridge","sidePlank"]]},
 "Enhanced core":{icon:"◉",title:"Core control",desc:"Build a stronger, steadier centre.",promise:"Front, side, back and coordination core with only verified real-person media.",rotations:[["plank","deadbug","sidePlank","birdDog","bridge"],["deadbug","plank","birdDog","sidePlank","calfRaise"],["sidePlank","deadbug","bridge","plank","birdDog"]]},
 "Knee strength":{icon:"◇",title:"Knee support",desc:"Low-impact strength around knees and ankles.",promise:"Squat, hip and calf support with conservative pacing.",rotations:[["squat","bridge","calfRaise","deadbug"],["bridge","squat","calfRaise","birdDog"],["calfRaise","squat","bridge","sidePlank"]]},
 "Upper body":{icon:"↑",title:"Upper-body builder",desc:"Chest, shoulders, back and trunk stability.",promise:"Push strength plus trunk work so shoulders stay supported.",rotations:[["push","plank","birdDog","sidePlank"],["plank","push","deadbug","birdDog"],["push","sidePlank","plank","bridge"]]},
 "Lower body":{icon:"↓",title:"Lower-body power",desc:"Legs, glutes, hips and balance.",promise:"More leg-day flavor using tempo, holds and balance challenges.",rotations:[["squat","bridge","calfRaise","deadbug"],["bridge","calfRaise","squat","sidePlank"],["squat","birdDog","bridge","calfRaise"]]},
 "Arm strength":{icon:"↗",title:"Arm strength",desc:"Progressive pushing and shoulder stability.",promise:"Simple pressing progressions with core bracing built in.",rotations:[["push","plank","sidePlank","birdDog"],["push","deadbug","plank","bridge"],["plank","push","sidePlank","calfRaise"]]},
 "Mobility & Recovery":{icon:"☾",title:"Move better",desc:"Low-stress control for stiff days.",promise:"Gentle strength, breathing and joint confidence.",rotations:[["bridge","deadbug","birdDog","calfRaise"],["deadbug","bridge","squat","birdDog"],["calfRaise","birdDog","sidePlank","bridge"]]},
 "No-jump Conditioning":{icon:"⚡",title:"Quiet sweat",desc:"Apartment-friendly conditioning without jumping.",promise:"Higher pace, still no pounding.",rotations:[["squat","push","calfRaise","plank","bridge"],["push","squat","sidePlank","calfRaise","deadbug"],["plank","squat","push","birdDog","bridge"]]},
 "Skill Prep":{icon:"✦",title:"Skill prep",desc:"Earn future calisthenics milestones.",promise:"Foundations for push-up, L-sit, plank and balance skills.",rotations:[["plank","push","deadbug","sidePlank","birdDog"],["push","plank","bridge","deadbug","calfRaise"],["sidePlank","birdDog","push","squat","plank"]]}
};
type Goal=keyof typeof goals; const ages=["13–17","18–29","30–44","45–59","60+"]; const nav:Tab[]=["Today","Plan","Community","Progress"];
const vault=["Wall push-up","Incline push-up","Slow negative push-up","Knee plank","Forearm plank","Long-lever plank","Sit-to-stand","Tempo squat","Squat pulse","Glute bridge hold","Marching bridge","Single-leg bridge prep","Supported calf raise","Slow calf raise","Heel taps","Dead bug","Dead bug pause","Short side plank","Side plank hold","Side plank reach","Three-point hold","Bird dog","Bird dog hover","Quiet conditioning circuit","Recovery reset","Skill prep flow"];
function workTime(base:number,age:string,level:Level,readiness:Readiness){const a:Record<string,number>={"13–17":.9,"18–29":1,"30–44":1,"45–59":.9,"60+":.78},l:Record<Level,number>={Beginner:.82,Intermediate:1,Advanced:1.18},r:Record<Readiness,number>={Recover:.72,Ready:1,Push:1.12};return Math.max(20,Math.round(base*a[age]*l[level]*r[readiness]/5)*5)}
function MovementMedia({move,large=false}:{move:Move;large?:boolean}){return <div className={"movement-media "+(large?"large":"")}><video src={move.video} poster={move.image} autoPlay loop muted playsInline preload={large?"auto":"metadata"} aria-label={move.name+" real-person movement demonstration"}/><div className="media-shade"/>{move.credit&&<span className="media-credit">{move.credit}</span>}<span className="loop-badge">↻ LOOP</span></div>}
export default function Home(){
 const[goal,setGoal]=useState<Goal>("Full body"),[age,setAge]=useState("30–44"),[sex,setSex]=useState<Sex>("Prefer not to say"),[level,setLevel]=useState<Level>("Beginner"),[readiness,setReadiness]=useState<Readiness>("Ready");
 const[profile,setProfile]=useState(false),[adapt,setAdapt]=useState(false),[session,setSession]=useState(false),[finish,setFinish]=useState(false),[showWhy,setShowWhy]=useState(false),[running,setRunning]=useState(false),[active,setActive]=useState(0),[left,setLeft]=useState(0),[tab,setTab]=useState<Tab>("Today"),[targetMinutes,setTargetMinutes]=useState(20),[quiet,setQuiet]=useState(false),[caption,setCaption]=useState(true),[audioHints,setAudioHints]=useState(true),[kudos,setKudos]=useState(18),[rotation,setRotation]=useState(0);
 const goalData=goals[goal],keys=goalData.rotations[rotation%goalData.rotations.length],plan=useMemo(()=>keys.map((k,i)=>({...M[k],seconds:workTime(M[k].base+(i%2?5:0),age,level,readiness)})),[keys,age,level,readiness]),minutes=targetMinutes,current=plan[active]||plan[0],freshness=Math.min(96,62+rotation*7+Object.keys(goals).indexOf(goal)*2);
 useEffect(()=>{const raw=localStorage.getItem("bodywise-profile");if(raw){try{const p=JSON.parse(raw);if(p.goal&&goals[p.goal as Goal])setGoal(p.goal);if(p.age)setAge(p.age);if(p.sex)setSex(p.sex);if(p.level)setLevel(p.level)}catch{}}},[]);
 useEffect(()=>{if(!running||left<=0)return;const t=window.setInterval(()=>setLeft(v=>v-1),1000);return()=>clearInterval(t)},[running,left]); useEffect(()=>{if(session)setLeft(current.seconds)},[active,current.seconds,session]);
 function chooseGoal(next:Goal){setGoal(next);setActive(0);setSession(false);setRunning(false);setRotation(0)} function saveProfile(){localStorage.setItem("bodywise-profile",JSON.stringify({goal,age,sex,level}));setProfile(false)} function start(){setActive(0);setLeft(plan[0].seconds);setRunning(true);setFinish(false);setSession(true)} function next(){if(active===plan.length-1){setSession(false);setRunning(false);setFinish(true)}else{setActive(v=>v+1);setRunning(true)}}
 return <main className="app-shell">
  <header className="topbar premium-topbar"><button className="brand" onClick={()=>setTab("Today")} aria-label="Bodywise home"><b>B</b>BODYWISE</button><div className="top-actions"><span className="streak-pill">⚡ {freshness}% FRESH</span><button className="profile-pill" onClick={()=>setProfile(true)} aria-label="Open training profile"><span>{age}</span><b>{sex==="Female"?"F":sex==="Male"?"M":"·"}</b></button></div></header>
  {tab==="Today"&&<><section className="intro home-hero"><div className="hero-date"><p className="eyebrow">ROTATION {rotation+1} · WEEK 2</p><span>{goal.toUpperCase()}</span></div><h1>Never the<br/><em>same.</em></h1><p>Choose a target, spin a fresh bodyweight session, and follow real-person movement loops from the first second.</p><div className="hero-proof"><span><b>{vault.length}</b> variations mapped</span><span><b>{plan.length}</b> moves today</span></div></section>
  <section className="coach-note"><div className="coach-avatar">K</div><div><small>COACH KAI · VARIETY ENGINE</small><b>{goalData.promise}</b><p>Each target has multiple rotations so users keep seeing new sessions without losing progression.</p></div></section>
  <section className="readiness-row"><div><p className="eyebrow">HOW DO YOU FEEL?</p><h2>Set today’s pace</h2></div><div>{(["Recover","Ready","Push"] as Readiness[]).map(x=><button key={x} className={readiness===x?"selected":""} onClick={()=>setReadiness(x)}>{x}</button>)}</div></section>
  <section className="target-section"><div className="target-heading"><div><p className="eyebrow">SELECT A TARGET</p><h2>What are we building?</h2></div><b>{Object.keys(goals).length} GOALS</b></div><div className="target-grid">{(Object.keys(goals) as Goal[]).map(name=><button className={goal===name?"selected":""} onClick={()=>chooseGoal(name)} key={name}><i>{goals[name].icon}</i><span>{name}</span><small>{goals[name].desc}</small>{goal===name&&<b>✓</b>}</button>)}</div>{goal==="Knee strength"&&<p className="knee-note">Knee work should feel controlled, not painful. If pain persists, ask a qualified clinician.</p>}</section>
  <section className="variety-card"><div><p className="eyebrow">ANTI-BOREDOM MODE</p><h2>Spin a fresh session</h2><p>Same target, different order, different emphasis, real-person demos only.</p></div><button onClick={()=>{setRotation(v=>(v+1)%3);setActive(0)}}>Shuffle today ↻</button><div className="fresh-meter"><i style={{width:freshness+"%"}}/><span>{freshness}% freshness</span></div></section>
  <section className="workout featured-workout"><img src={plan[0].image} alt={goal+" workout"}/><div className="shade"/><div className="workout-copy"><span className="tag">TODAY’S RECOMMENDATION</span><div className="coach-byline"><i>K</i><span>Coach Kai · {readiness} pace · Rotation {rotation+1}</span></div><h2>{goalData.title}</h2><p>{quiet?"Quiet mode is on: no jumping and apartment-friendly movement.":goalData.desc}</p><div className="stats"><span><b>{minutes}</b> min</span><span><b>{plan.length}</b> moves</span><span><b>3</b> rounds</span></div></div><button className="start" onClick={start}>Start today’s workout <b>→</b></button></section>
  <button className="adapt-today" onClick={()=>setAdapt(true)}><span>⚙</span><div><b>Adapt today</b><small>Change time, space or intensity</small></div><i>→</i></button>
  <section className="packs"><p className="eyebrow">MOVEMENT FAMILIES</p><h2>More variety, less randomness</h2><div>{plan.map(x=><article key={x.name}><MovementMedia move={x}/><div><small>{x.family} · {x.intensity}</small><h3>{x.name}</h3><p>{x.why}</p><div>{x.variants.map(v=><span key={v}>{v}</span>)}</div></div></article>)}</div></section>
  <section className="recovery-card"><div><p className="eyebrow">ESTIMATED RECOVERY</p><h2>Your body map</h2><small>Based on recent sessions—not a medical measurement.</small></div><div className="recovery-bars"><span><i style={{width:"82%"}}/>Core <b>82%</b></span><span><i style={{width:"64%"}}/>Upper <b>64%</b></span><span><i style={{width:"91%"}}/>Lower <b>91%</b></span></div><button className="why-button" onClick={()=>setShowWhy(v=>!v)} aria-expanded={showWhy}>{showWhy?"Hide":"Why this workout?"}<b>{showWhy?"−":"+"}</b></button>{showWhy&&<div className="why-copy"><b>Why Bodywise chose this</b><p>This rotation matches your {goal} target, {readiness} pace, age range and current time window. Only verified real-person media is used in this version.</p></div>}</section>
  <section className="vault-card"><div><p className="eyebrow">MOVE VAULT</p><h2>{vault.length} ways to keep growing</h2><p>These are programmed as progressions and swaps around the verified real-human movement families.</p></div><div>{vault.map(v=><span key={v}>{v}</span>)}</div></section>
  <section className="section-head"><div><p className="eyebrow">YOUR TARGETED PLAN</p><h2>{goal} movements</h2></div><span>{plan.length} selected</span></section><section className="exercise-list">{plan.map((x,i)=><article className="exercise" key={x.name}><div className="exercise-image"><MovementMedia move={x}/></div><div className="exercise-copy"><small>0{i+1} · {x.focus}</small><h3>{x.name}</h3><p>{x.cue}</p><span>Watch the real-person loop, then match its controlled pace.</span></div><aside><b>{x.seconds}</b><small>SEC</small></aside></article>)}</section></>}
  {tab==="Plan"&&<PlanPage goal={goal} minutes={minutes}/>} {tab==="Community"&&<CommunityPage kudos={kudos} onKudos={()=>setKudos(v=>v+1)}/>} {tab==="Progress"&&<ProgressPage goal={goal}/>} 
  <nav className="bottom-nav provider-nav">{nav.map((x,i)=><button className={tab===x?"selected":""} onClick={()=>setTab(x)} key={x}><span>{["●","▤","◎","◔"][i]}</span>{x}</button>)}</nav>
  {adapt&&<div className="overlay" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setAdapt(false)} aria-label="Close"/><section className="sheet adapt-sheet"><i/><button className="close" onClick={()=>setAdapt(false)}>×</button><p className="eyebrow">FREE UP THE PLAN</p><h2>Adapt today.</h2><fieldset><legend>Time available</legend><div className="choices">{[10,15,20].map(x=><button className={targetMinutes===x?"chosen":""} onClick={()=>setTargetMinutes(x)} key={x}>{x} min</button>)}</div></fieldset><fieldset><legend>Energy</legend><div className="choices">{(["Recover","Ready","Push"] as Readiness[]).map(x=><button className={readiness===x?"chosen":""} onClick={()=>setReadiness(x)} key={x}>{x}</button>)}</div></fieldset><label className="quiet-toggle"><span><b>Quiet mode</b><small>No jumping · small-space friendly</small></span><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/></label><button className="save" onClick={()=>setAdapt(false)}>Update today’s workout</button></section></div>}
  {profile&&<div className="overlay" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setProfile(false)} aria-label="Close"/><section className="sheet"><i/><button className="close" onClick={()=>setProfile(false)}>×</button><p className="eyebrow">PERSONALISE YOUR START</p><h2>Make the plan yours.</h2><p className="note">Age and experience tune the starting pace. Sex is optional health context and does not change your workout.</p><fieldset><legend>Training target</legend><div className="choices target-choices">{(Object.keys(goals) as Goal[]).map(x=><button className={goal===x?"chosen":""} onClick={()=>chooseGoal(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Age range</legend><div className="choices ages">{ages.map(x=><button className={age===x?"chosen":""} onClick={()=>setAge(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Sex · optional health context</legend><div className="choices">{(["Female","Male","Prefer not to say"] as Sex[]).map(x=><button className={sex===x?"chosen":""} onClick={()=>setSex(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Experience</legend><div className="choices">{(["Beginner","Intermediate","Advanced"] as Level[]).map(x=><button className={level===x?"chosen":""} onClick={()=>setLevel(x)} key={x}>{x}</button>)}</div></fieldset><div className="preview"><span>{goal} practice</span><b>{minutes} min · {plan.length} targeted movements · {vault.length} vault variations</b></div><button className="save" onClick={saveProfile}>Save my plan</button></section></div>}
  {session&&<section className="session premium-session" role="dialog" aria-modal="true"><header><button onClick={()=>{setSession(false);setRunning(false)}}>×</button><span>{goal.toUpperCase()} · MOVE {active+1} OF {plan.length}</span><button>◒</button></header><div className="live-metrics"><span><small>HEART RATE · DEMO</small><b>124 <i>BPM</i></b></span><span><small>EFFORT · DEMO</small><b>6 <i>/10</i></b></span><span><small>ACTIVE · DEMO</small><b>38 <i>KCAL</i></b></span></div><div className="session-title"><p>{current.family}</p><h2>{current.name}</h2></div><div className="session-visual"><MovementMedia move={current} large/></div><div className="session-tools"><button className={audioHints?"on":""} onClick={()=>setAudioHints(v=>!v)}>◖ Audio hints</button><button className={caption?"on":""} onClick={()=>setCaption(v=>!v)}>CC Captions</button><button onClick={()=>setRotation(v=>(v+1)%3)}>◐ Swap</button><button>♫ Focus mix</button></div>{caption&&<p className="caption">{current.detail}</p>}<div className="cue"><span>COACH KAI</span><b>{current.cue}</b><p>{audioHints?"Audio hint on · ":""}{current.detail}</p></div><div className="timer-row"><div className="timer" style={{background:"conic-gradient(#e8ff48 "+((current.seconds-left)/current.seconds*100)+"%,#2e302a 0)"}}><div><b>{left}</b><span>SECONDS</span></div></div><button onClick={()=>setRunning(v=>!v)}>{running?"Ⅱ":"▶"}<span>{running?"Pause":"Resume"}</span></button><button className="next" onClick={next}>→<span>{active===plan.length-1?"Finish":"Next"}</span></button></div><div className="session-progress"><i style={{width:((active+1)/plan.length*100)+"%"}}/></div></section>}
  {finish&&<div className="overlay finish" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setFinish(false)} aria-label="Close"/><section className="finish-card"><span>✓</span><p className="eyebrow">SESSION COMPLETE</p><h2>Strong work.</h2><p>You kept the promise you made to yourself today. Next time, spin a new rotation to keep it fresh.</p><div className="summary-metrics"><b>{minutes}<small>MIN</small></b><b>{plan.length}<small>MOVES</small></b><b>+1<small>STREAK</small></b></div><div className="rating"><small>HOW DID THAT FEEL?</small><div>{["Too easy","Just right","Too hard"].map(x=><button key={x}>{x}</button>)}</div></div><button className="share-result" onClick={()=>setRotation(v=>(v+1)%3)}>Unlock next variation</button><button className="done" onClick={()=>setFinish(false)}>Done</button></section></div>}
 </main>}
function PlanPage({goal,minutes}:{goal:Goal;minutes:number}){const days=[{d:"MON",n:"14",s:"DONE",t:"Foundation"},{d:"TUE",n:"15",s:"REST",t:"Mobility"},{d:"WED",n:"16",s:"TODAY",t:goal},{d:"FRI",n:"18",s:"UP NEXT",t:"Fresh rotation"},{d:"SUN",n:"20",s:"OPTIONAL",t:"Skill prep"}];return <section className="platform-page plan-page"><p className="eyebrow">YOUR CUSTOM PLAN</p><h1>Stay<br/><em>curious.</em></h1><p className="page-lede">A flexible week that rotates movement families so users get novelty without losing structure.</p><div className="plan-summary"><span><b>3</b> days / week</span><span><b>{minutes}</b> min / session</span><span><b>9</b> goal packs</span></div><div className="week-plan">{days.map(x=><article className={x.s==="TODAY"?"today":""} key={x.d}><div><small>{x.d}</small><b>{x.n}</b></div><span>{x.s}</span><h3>{x.t}</h3><p>{x.s==="REST"?"Breathe · stretch · walk":minutes+" min · Coach Kai"}</p>{x.s==="TODAY"&&<button>Start →</button>}</article>)}</div><div className="plan-controls"><h2>Plan upgrades</h2><button><span>Rotation logic</span><b>3 versions per goal →</b></button><button><span>Boredom guard</span><b>Shuffle + vault →</b></button><button><span>Media promise</span><b>Real-person only →</b></button></div><div className="coach-program"><span>COACH KAI · BLOCK 1</span><h2>Own the basics, then vary them.</h2><p>The app now teaches families, progressions and swaps — the part that keeps people from quitting after week one.</p><i>WEEK 2 OF 4</i></div></section>}
function CommunityPage({kudos,onKudos}:{kudos:number;onKudos:()=>void}){return <section className="platform-page community-page"><p className="eyebrow">BODYWISE CLUB</p><h1>Better<br/><em>together.</em></h1><p className="page-lede">A supportive, opt-in space for showing up — with weekly variety challenges.</p><article className="challenge"><span>THIS WEEK’S CHALLENGE</span><h2>Try 3 different rotations.</h2><div><i style={{width:"58%"}}/></div><p><b>7</b> of 12 sessions · 13 days left</p><button>View challenge →</button></article><div className="club-strip"><span><b>2,418</b> members</span><span><b>386</b> trained today</span><span><b>94%</b> supportive</span></div><div className="feed"><h2>Club feed</h2><article><div className="member">AR</div><div><b>Amara R.</b><small>2 HOURS AGO · CORE CONTROL</small><p>The side plank rotation finally made core day feel different.</p><button onClick={onKudos}>▲ {kudos} kudos</button><button>Reply</button></div></article><article><div className="member rust">JL</div><div><b>Jon L.</b><small>YESTERDAY · QUIET SWEAT</small><p>Quiet conditioning in a hotel room. Zero jumping, still sweaty.</p><button>▲ 24 kudos</button><button>Reply</button></div></article></div><p className="privacy-note">Community sharing is opt-in. Your age, sex and health context stay private.</p></section>}
function ProgressPage({goal}:{goal:Goal}){return <section className="platform-page progress-page"><p className="eyebrow">YOUR PROGRESS</p><h1>Proof of<br/><em>practice.</em></h1><p className="page-lede">Track consistency, capacity, movement variety and the skills you are earning.</p><div className="score-grid"><article><span>THIS WEEK</span><b>3<small>/3</small></b><p>sessions complete</p></article><article><span>VARIETY SCORE</span><b>84<small>%</small></b><p>new movement exposure</p></article><article><span>TRAINING TIME</span><b>62<small> MIN</small></b><p>+14% vs last week</p></article><article><span>FOCUS</span><b className="focus-score">{goal}</b><p>current block</p></article></div><article className="load-chart"><div><span>TRAINING LOAD</span><b>Balanced</b></div><div className="bars">{[42,61,36,78,58,90,70].map((x,i)=><i key={i} style={{height:x+"%"}}/>)}</div>{["MON","TUE","WED","THU","FRI","SAT","SUN"].map(x=><small key={x}>{x}</small>)}</article><article className="skill-path"><span>SKILL PATH · PUSH-UP</span><h2>Build it one step at a time.</h2>{["Wall push-up","Incline push-up","Slow negative","Full push-up"].map((x,i)=><div className={i<2?"done":i===2?"current":""} key={x}><i>{i<2?"✓":i+1}</i><span><b>{x}</b><small>{i<2?"Mastered":i===2?"In progress · 68%":"Locked"}</small></span></div>)}</article><article className="latest-win"><span>YOUR LATEST WIN</span><h2>Unlocked rotation variety</h2><p>More choices, same bodyweight foundation, real-person media only.</p><button>Share achievement →</button></article></section>}