"use client";
import {useEffect,useMemo,useState} from "react";
type Sex="Female"|"Male"|"Prefer not to say"; type Level="Beginner"|"Intermediate"|"Advanced"; type Readiness="Recover"|"Ready"|"Push"; type Tab="Today"|"Plan"|"Community"|"Progress";
type Move={name:string;focus:string;family:string;intensity:"Low"|"Medium"|"High";base:number;image:string;video:string;credit?:string;cue:string;detail:string;variants:string[];why:string};
const M:Record<string,Move>={
 push:{name:"Incline push-up",focus:"Chest · arms",family:"Push strength",intensity:"Medium",base:35,image:"/pushup-real.jpg",video:"/pushup-loop.mp4",cue:"Body in one long line",detail:"Hands just wider than shoulders. Lower with control, then press away.",variants:["Wall push-up","Incline push-up","Slow negative push-up","Full push-up prep"],why:"Builds pressing strength without jumping or equipment."},
 wallPush:{name:"Wall push-up",focus:"Beginner chest · arms",family:"Push strength",intensity:"Low",base:30,image:"/pushup-real.jpg",video:"/bodywise-wall-pushup-demo.mp4",credit:"Bodywise Original Demo",cue:"Stand tall and press away",detail:"Hands on the wall at chest height. Keep your body long, bend elbows toward the wall, then press away with control.",variants:["Wall push-up","Counter push-up","High incline push-up","Incline push-up"],why:"The safest starting point for brand-new users or recovery days."},
 slowPush:{name:"Slow negative push-up",focus:"Chest · triceps control",family:"Push strength",intensity:"High",base:30,image:"/pushup-real.jpg",video:"/pushup-loop.mp4",cue:"Lower for three counts",detail:"Match the real-person push-up line, but make the lowering phase slower than the press.",variants:["Incline negative","Knee negative","Full negative","Pause push-up"],why:"Adds strength without needing extra equipment."},
 plankTap:{name:"Plank shoulder tap prep",focus:"Shoulders · anti-rotation",family:"Push + core",intensity:"Medium",base:25,image:"/plank-real.jpg",video:"/bodywise-plank-shoulder-taps-demo.mp4",credit:"Bodywise Original Demo",cue:"Keep hips quiet",detail:"Hold a high plank, keep feet slightly apart, and tap the opposite shoulder without rocking the hips.",variants:["High plank hold","Weight shift","Shoulder tap prep","Alternating shoulder taps"],why:"Builds shoulder stability and anti-rotation control."},
 squat:{name:"Bodyweight squat",focus:"Quads · glutes",family:"Knee + hip pattern",intensity:"Medium",base:40,image:"/squat-real.jpg",video:"/squat-loop.mp4",cue:"Knees track over toes",detail:"Sit hips back and down. Keep your whole foot grounded and chest tall.",variants:["Sit-to-stand","Tempo squat","Squat pulse","Squat-to-reach"],why:"The base pattern for knees, hips, stairs and daily strength."},
 sitStand:{name:"Sit-to-stand",focus:"Knee confidence",family:"Knee + hip pattern",intensity:"Low",base:35,image:"/squat-real.jpg",video:"/bodywise-sit-to-stand-demo.mp4",credit:"Bodywise Original Demo",cue:"Stand through your whole foot",detail:"Start seated, plant both feet, stand fully tall without using hands, then lower back to the chair with control.",variants:["High chair stand","Chair tap squat","Bodyweight squat","Tempo squat"],why:"Great for older users, beginners, and knee-friendly strength."},
 squatPulse:{name:"Squat pulse",focus:"Quads · glute endurance",family:"Knee + hip pattern",intensity:"High",base:25,image:"/squat-real.jpg",video:"/squat-loop.mp4",cue:"Small range, steady knees",detail:"Use the squat loop as the base. Stay in the comfortable bottom half for short controlled pulses.",variants:["Half squat hold","Squat pulse","Tempo squat","Squat-to-reach"],why:"Adds lower-body burn without jumping."},
 squatReach:{name:"Squat-to-reach",focus:"Legs · mobility",family:"Mobility strength",intensity:"Medium",base:35,image:"/squat-real.jpg",video:"/squat-loop.mp4",cue:"Reach tall after each rep",detail:"Squat with control, then stand and reach overhead to open hips and ribs.",variants:["Quarter squat reach","Squat-to-reach","Tempo reach squat","Flow squat"],why:"Makes leg work feel more athletic and less repetitive."},
 bridge:{name:"Glute bridge",focus:"Glutes · hamstrings",family:"Posterior chain",intensity:"Low",base:40,image:"/bridge-real.jpg",video:"/bridge-loop.mp4",cue:"Lift from the hips",detail:"Press through heels. Pause at the top without arching your lower back.",variants:["Glute bridge hold","Marching bridge","Single-leg bridge prep","Long bridge"],why:"Wakes up glutes and hamstrings for knee and back support."},
 bridgeMarch:{name:"Marching bridge",focus:"Glutes · pelvic control",family:"Posterior chain",intensity:"Medium",base:30,image:"/bridge-real.jpg",video:"/bodywise-marching-bridge-demo.mp4",credit:"Bodywise Original Demo",cue:"Hips stay level",detail:"Lift into a bridge, then alternate lifting one foot while keeping the pelvis steady and controlled.",variants:["Bridge hold","Tiny march","Marching bridge","Single-leg bridge prep"],why:"Adds coordination and glute endurance beyond a basic bridge."},
 singleBridge:{name:"Single-leg bridge prep",focus:"Glutes · hamstrings",family:"Posterior chain",intensity:"High",base:25,image:"/bridge-real.jpg",video:"/bridge-loop.mp4",cue:"Press one heel heavy",detail:"Use the bridge loop as the base pattern. Keep the pelvis level before trying a full single-leg bridge.",variants:["Bridge hold","Kickstand bridge","Single-leg bridge prep","Single-leg bridge"],why:"A stronger progression for hips, hamstrings and knee support."},
 calfRaise:{name:"Standing calf raise",focus:"Calves · ankle support",family:"Ankle + balance",intensity:"Low",base:35,image:"/calf-raise-real.jpg",video:"https://wger.de/media/exercise-video/622/35b7b625-77fd-4c09-8c57-3ad0f2f23175.MOV",credit:"WGER · real-person demo",cue:"Rise tall, lower slowly",detail:"Use support if needed and keep weight even across both feet.",variants:["Supported calf raise","Slow eccentric calf raise","Single-leg calf prep","Calf raise balance hold"],why:"Strengthens ankles and lower-leg support for walking, stairs and knee confidence."},
 ankleRocks:{name:"Ankle rockers",focus:"Ankles · mobility",family:"Mobility strength",intensity:"Low",base:30,image:"/calf-raise-real.jpg",video:"https://wger.de/media/exercise-video/622/35b7b625-77fd-4c09-8c57-3ad0f2f23175.MOV",credit:"WGER · real-person demo",cue:"Move slowly through the ankle",detail:"Use the calf raise setup. Rock gently from mid-foot to toes without bouncing.",variants:["Supported ankle rocks","Calf raise hold","Slow calf raise","Balance calf raise"],why:"A simple finisher for ankle range and lower-leg circulation."},
 deadbug:{name:"Dead bug",focus:"Deep core control",family:"Coordination core",intensity:"Low",base:35,image:"/dead-bug-real.jpg",video:"/dead-bug-real.mp4",credit:"Cureus open-access supplement · CC BY",cue:"Lower back stays heavy",detail:"Move opposite arm and leg slowly. Exhale as they reach away.",variants:["Heel taps","Dead bug","Dead bug pause","Long-lever dead bug"],why:"Excellent beginner-safe core control without neck strain."},
 heelTaps:{name:"Heel taps",focus:"Beginner deep core",family:"Coordination core",intensity:"Low",base:30,image:"/dead-bug-real.jpg",video:"/dead-bug-real.mp4",credit:"Cureus open-access supplement · CC BY",cue:"Tap light, brace heavy",detail:"Use the dead bug loop as the setup. Tap one heel down while keeping ribs soft.",variants:["Bent-knee brace","Heel taps","Dead bug","Long-lever dead bug"],why:"A beginner-friendly bridge into harder core work."},
 longDeadbug:{name:"Long-lever dead bug",focus:"Deep core endurance",family:"Coordination core",intensity:"High",base:25,image:"/dead-bug-real.jpg",video:"/dead-bug-real.mp4",credit:"Cureus open-access supplement · CC BY",cue:"Reach longer, not faster",detail:"Use the dead bug loop, extending limbs farther only if the lower back stays controlled.",variants:["Dead bug","Dead bug pause","Long-lever dead bug","Hollow-body prep"],why:"Adds challenge to the core without needing crunches."},
 plank:{name:"Forearm plank",focus:"Deep core · shoulders",family:"Anti-extension core",intensity:"Medium",base:30,image:"/plank-real.jpg",video:"/plank-loop.mp4",cue:"Brace, breathe, stay long",detail:"Stack elbows under shoulders and keep your neck neutral.",variants:["Knee plank","Forearm plank","Long-lever plank","Plank shoulder tap prep"],why:"Trains the trunk to resist arching and protect the lower back."},
 kneePlank:{name:"Knee plank",focus:"Beginner core · shoulders",family:"Anti-extension core",intensity:"Low",base:30,image:"/plank-real.jpg",video:"/plank-loop.mp4",cue:"Shorter body, same brace",detail:"Use the plank loop as the target shape, but keep knees down to reduce load.",variants:["Knee plank","Forearm plank","Long-lever plank","Plank saw prep"],why:"Lets beginners practice good plank alignment safely."},
 longPlank:{name:"Long-lever plank",focus:"Advanced core",family:"Anti-extension core",intensity:"High",base:20,image:"/plank-real.jpg",video:"/plank-loop.mp4",cue:"Stay long without sagging",detail:"Use the plank loop, then inch elbows slightly forward only if form stays clean.",variants:["Forearm plank","Long-lever plank","Plank saw prep","Body saw"],why:"A serious calisthenics core progression."},
 bearHold:{name:"Bear crawl hold",focus:"Core · shoulders · hips",family:"Animal strength",intensity:"Medium",base:25,image:"/bird-dog-real.jpg",video:"/bodywise-bear-hold-demo.mp4",credit:"Bodywise Original Demo",cue:"Knees hover low",detail:"Stack hands under shoulders and knees under hips, then hover knees just above the mat while breathing steadily.",variants:["Quadruped brace","Bear hold","Bear shoulder taps","Bear crawl prep"],why:"Adds a fresh full-body floor pattern without jumping."},
 birdDog:{name:"Bird dog",focus:"Core · back control",family:"Back + trunk stability",intensity:"Low",base:35,image:"/bird-dog-real.jpg",video:"/bird-dog-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Reach without twisting",detail:"Extend opposite arm and leg while keeping hips level.",variants:["Three-point hold","Bird dog","Bird dog elbow-to-knee","Slow bird dog hover"],why:"Balances core training with back-side stability and posture work."},
 birdDogCrunch:{name:"Bird dog crunch",focus:"Back · core coordination",family:"Back + trunk stability",intensity:"Medium",base:30,image:"/bird-dog-real.jpg",video:"/bird-dog-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Round and reach with control",detail:"Use the bird dog loop. Add a slow elbow-to-knee return only if hips stay level.",variants:["Bird dog hold","Bird dog","Bird dog crunch","Hover bird dog"],why:"Makes posture work feel more dynamic."},
 sidePlank:{name:"Side plank",focus:"Obliques · waist",family:"Side-core strength",intensity:"Medium",base:25,image:"/side-plank-real.jpg",video:"/side-plank-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Lift the underside waist",detail:"Stack shoulder over elbow and keep your body long.",variants:["Short side plank","Side plank hold","Side plank reach","Star plank prep"],why:"Targets obliques and lateral hip control that front planks miss."},
 shortSide:{name:"Short side plank",focus:"Beginner side core",family:"Side-core strength",intensity:"Low",base:25,image:"/side-plank-real.jpg",video:"/side-plank-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Knees bent, waist lifted",detail:"Use the side plank loop, keeping knees down for a shorter lever.",variants:["Short side plank","Side plank hold","Side plank reach","Star plank prep"],why:"A safer entry point for oblique and shoulder strength."},
 sideReach:{name:"Side plank reach",focus:"Obliques · shoulder control",family:"Side-core strength",intensity:"High",base:20,image:"/side-plank-real.jpg",video:"/side-plank-real.mp4",credit:"Frontiers open-access supplement · CC BY",cue:"Reach without collapsing",detail:"Use the side plank loop, then add a controlled top-arm reach if stable.",variants:["Side plank hold","Side plank reach","Side plank rotation prep","Star plank prep"],why:"Adds challenge and variety to core days."},
 quietMarch:{name:"Quiet high-knee march",focus:"No-jump conditioning",family:"Quiet conditioning",intensity:"Medium",base:35,image:"/squat-real.jpg",video:"/squat-loop.mp4",cue:"Drive knees, land soft",detail:"Use the standing lower-body setup. March in place with tall posture and quiet feet.",variants:["March in place","High-knee march","Fast march","March + reach"],why:"Adds cardio flavor without jumping or annoying downstairs neighbors."},
 flowReset:{name:"Recovery reset flow",focus:"Mobility · breathing",family:"Mobility strength",intensity:"Low",base:40,image:"/bridge-real.jpg",video:"/bridge-loop.mp4",cue:"Move like you are warming joints",detail:"Alternate bridge breathing, easy squats and quadruped reaches at a relaxed pace.",variants:["Bridge breathing","Quadruped reach","Easy squat","Ankle rocks"],why:"Makes the app useful even on stiff or tired days."},
 skillPrep:{name:"Calisthenics skill flow",focus:"Skill prep · coordination",family:"Skill prep",intensity:"Medium",base:35,image:"/plank-real.jpg",video:"/plank-loop.mp4",cue:"Own each shape",detail:"Use plank, push-up and core positions as clean shapes before chasing advanced skills.",variants:["Plank line","Push-up line","L-sit tuck prep","Crow-prep balance"],why:"Gives users milestones to chase, not just calories to burn."}
};
const goals={
 "Full body":{icon:"◎",title:"Full-body foundation",desc:"Balanced strength from head to toe.",promise:"A complete baseline that never hammers one area too hard.",rotations:[["push","squat","plank","bridge","deadbug","birdDog","calfRaise"],["sitStand","slowPush","sidePlank","bridgeMarch","ankleRocks","heelTaps"],["plankTap","squatReach","birdDogCrunch","singleBridge","shortSide","quietMarch"]]},
 "Enhanced core":{icon:"◉",title:"Core control",desc:"Build a stronger, steadier centre.",promise:"Front, side, back and coordination core with only verified real-person media.",rotations:[["plank","deadbug","sidePlank","birdDog","bridge"],["heelTaps","kneePlank","birdDogCrunch","shortSide","bridgeMarch"],["longPlank","longDeadbug","sideReach","bearHold","birdDog"]]},
 "Knee strength":{icon:"◇",title:"Knee support",desc:"Low-impact strength around knees and ankles.",promise:"Squat, hip and calf support with conservative pacing.",rotations:[["sitStand","bridge","calfRaise","deadbug"],["squat","bridgeMarch","ankleRocks","birdDog"],["squatPulse","singleBridge","calfRaise","shortSide"]]},
 "Upper body":{icon:"↑",title:"Upper-body builder",desc:"Chest, shoulders, back and trunk stability.",promise:"Push strength plus trunk work so shoulders stay supported.",rotations:[["wallPush","plank","birdDog","shortSide"],["push","plankTap","deadbug","birdDogCrunch"],["slowPush","sideReach","longPlank","bridge"]]},
 "Lower body":{icon:"↓",title:"Lower-body power",desc:"Legs, glutes, hips and balance.",promise:"More leg-day flavor using tempo, holds and balance challenges.",rotations:[["sitStand","bridge","calfRaise","heelTaps"],["squat","bridgeMarch","ankleRocks","sidePlank"],["squatPulse","squatReach","singleBridge","quietMarch"]]},
 "Arm strength":{icon:"↗",title:"Arm strength",desc:"Progressive pushing and shoulder stability.",promise:"Simple pressing progressions with core bracing built in.",rotations:[["wallPush","kneePlank","shortSide","birdDog"],["push","plankTap","deadbug","bridge"],["slowPush","longPlank","sideReach","calfRaise"]]},
 "Mobility & Recovery":{icon:"☾",title:"Move better",desc:"Low-stress control for stiff days.",promise:"Gentle strength, breathing and joint confidence.",rotations:[["flowReset","heelTaps","birdDog","ankleRocks"],["bridge","squatReach","shortSide","birdDogCrunch"],["calfRaise","sitStand","deadbug","bridgeMarch"]]},
 "No-jump Conditioning":{icon:"⚡",title:"Quiet sweat",desc:"Apartment-friendly conditioning without jumping.",promise:"Higher pace, still no pounding.",rotations:[["quietMarch","squat","push","calfRaise","plank"],["squatPulse","plankTap","bridgeMarch","sidePlank","heelTaps"],["squatReach","slowPush","bearHold","ankleRocks","deadbug"]]},
 "Skill Prep":{icon:"✦",title:"Skill prep",desc:"Earn future calisthenics milestones.",promise:"Foundations for push-up, L-sit, plank and balance skills.",rotations:[["skillPrep","plank","push","deadbug","sidePlank"],["plankTap","slowPush","bridgeMarch","longDeadbug","calfRaise"],["longPlank","birdDogCrunch","sideReach","squatReach","bearHold"]]},
 "Balance & Posture":{icon:"◌",title:"Stand taller",desc:"Back, balance and joint-control practice.",promise:"Posture-friendly calisthenics for the back line, hips and ankles.",rotations:[["birdDog","calfRaise","bridge","sidePlank"],["birdDogCrunch","ankleRocks","bridgeMarch","heelTaps"],["bearHold","singleBridge","shortSide","flowReset"]]},
 "Beginner Basics":{icon:"●",title:"Start simple",desc:"Low-pressure foundations for new movers.",promise:"Clear entry points before users chase harder progressions.",rotations:[["wallPush","sitStand","kneePlank","heelTaps"],["shortSide","bridge","ankleRocks","birdDog"],["flowReset","calfRaise","deadbug","squatReach"]]}
};
type Goal=keyof typeof goals; const ages=["13–17","18–29","30–44","45–59","60+"]; const nav:Tab[]=["Today","Plan","Community","Progress"];
const vault=[
 {name:"Wall push-up",move:"wallPush",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Counter push-up",move:"wallPush",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Incline push-up",move:"push",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Slow negative push-up",move:"slowPush",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Pause push-up",move:"slowPush",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"High plank hold",move:"plank",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Knee plank",move:"kneePlank",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Forearm plank",move:"plank",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Long-lever plank",move:"longPlank",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Plank shoulder tap prep",move:"plankTap",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bear crawl hold",move:"bearHold",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Sit-to-stand",move:"sitStand",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Chair tap squat",move:"sitStand",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bodyweight squat",move:"squat",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Tempo squat",move:"squat",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Squat pulse",move:"squatPulse",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Squat-to-reach",move:"squatReach",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Quiet high-knee march",move:"quietMarch",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Glute bridge hold",move:"bridge",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Marching bridge",move:"bridgeMarch",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Kickstand bridge",move:"bridgeMarch",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Single-leg bridge prep",move:"singleBridge",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Supported calf raise",move:"calfRaise",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Slow eccentric calf raise",move:"calfRaise",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Single-leg calf prep",move:"calfRaise",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Ankle rockers",move:"ankleRocks",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Heel taps",move:"heelTaps",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bent-knee brace",move:"heelTaps",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Dead bug",move:"deadbug",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Dead bug pause",move:"deadbug",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Long-lever dead bug",move:"longDeadbug",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Tucked hollow hold",move:"longDeadbug",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Short side plank",move:"shortSide",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Side plank hold",move:"sidePlank",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Side plank reach",move:"sideReach",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Side plank rotation prep",move:"sideReach",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Three-point hold",move:"birdDog",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bird dog",move:"birdDog",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bird dog crunch",move:"birdDogCrunch",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bird dog hover",move:"birdDog",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Quadruped brace",move:"bearHold",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Recovery reset flow",move:"flowReset",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Bridge breathing",move:"bridge",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Mobility squat flow",move:"squatReach",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Calisthenics skill flow",move:"skillPrep",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"L-sit tuck prep",move:"skillPrep",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Crow-prep balance",move:"skillPrep",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Quiet conditioning circuit",move:"quietMarch",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Balance reset",move:"flowReset",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Posture builder",move:"birdDog",note:"Bodywise demo required. No borrowed placeholder."},
 {name:"Skill prep flow",move:"skillPrep",note:"Bodywise demo required. No borrowed placeholder."}
];
type VaultVideo={kind:"direct";src:string;credit:string;poster?:string;quality:"licensed"|"open-access"|"direct-source"|"bodywise-owned"};
const vaultExactVideos:Record<string,VaultVideo>={
 "Bodyweight squat":{kind:"direct",src:"/squat-loop.mp4",poster:"/squat-real.jpg",credit:"Bodywise direct real-person squat loop",quality:"direct-source"},
 "Wall push-up":{kind:"direct",src:"/bodywise-wall-pushup-demo.mp4",poster:"/pushup-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "Counter push-up":{kind:"direct",src:"/bodywise-wall-pushup-demo.mp4",poster:"/pushup-real.jpg",credit:"Bodywise Original Demo · wall/counter push pattern",quality:"bodywise-owned"},
 "Plank shoulder tap prep":{kind:"direct",src:"/bodywise-plank-shoulder-taps-demo.mp4",poster:"/plank-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "Bear crawl hold":{kind:"direct",src:"/bodywise-bear-hold-demo.mp4",poster:"/bird-dog-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "Quadruped brace":{kind:"direct",src:"/bodywise-bear-hold-demo.mp4",poster:"/bird-dog-real.jpg",credit:"Bodywise Original Demo · bear setup",quality:"bodywise-owned"},
 "Sit-to-stand":{kind:"direct",src:"/bodywise-sit-to-stand-demo.mp4",poster:"/squat-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "High chair stand":{kind:"direct",src:"/bodywise-sit-to-stand-demo.mp4",poster:"/squat-real.jpg",credit:"Bodywise Original Demo · sit-to-stand pattern",quality:"bodywise-owned"},
 "Chair tap squat":{kind:"direct",src:"/bodywise-chair-tap-squat-demo.mp4",poster:"/squat-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "Glute bridge hold":{kind:"direct",src:"/bridge-loop.mp4",poster:"/bridge-real.jpg",credit:"Bodywise direct real-person bridge loop",quality:"direct-source"},
 "Marching bridge":{kind:"direct",src:"/bodywise-marching-bridge-demo.mp4",poster:"/bridge-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "Kickstand bridge":{kind:"direct",src:"/bodywise-marching-bridge-demo.mp4",poster:"/bridge-real.jpg",credit:"Bodywise Original Demo · bridge progression",quality:"bodywise-owned"},
 "Supported calf raise":{kind:"direct",src:"https://wger.de/media/exercise-video/622/35b7b625-77fd-4c09-8c57-3ad0f2f23175.MOV",poster:"/calf-raise-real.jpg",credit:"wger direct real-person calf raise demo",quality:"open-access"},
 "Dead bug":{kind:"direct",src:"/dead-bug-real.mp4",poster:"/dead-bug-real.jpg",credit:"Cureus open-access supplement · CC BY",quality:"open-access"},
 "Tucked hollow hold":{kind:"direct",src:"/bodywise-tucked-hollow-demo.mp4",poster:"/dead-bug-real.jpg",credit:"Bodywise Original Demo",quality:"bodywise-owned"},
 "Side plank hold":{kind:"direct",src:"/side-plank-real.mp4",poster:"/side-plank-real.jpg",credit:"Frontiers open-access supplement · CC BY",quality:"open-access"},
 "Bird dog":{kind:"direct",src:"/bird-dog-real.mp4",poster:"/bird-dog-real.jpg",credit:"Frontiers open-access supplement · CC BY",quality:"open-access"}
};
const premiumSourcePlan=[
 {name:"MuscleWiki API",fit:"Best production-ready replacement",note:"1,900+ exercises and 7,500+ real demonstration videos; requires paid API key for direct app use."},
 {name:"Kinetic.place",fit:"Best premium/licensed media route",note:"Creator-shot fitness clips and API/bundle licensing for apps that need a polished branded feel."},
 {name:"YMove / Your Move",fit:"Best white-label app library lead",note:"1,021+ professional HD exercise videos with API access, direct temporary video URLs and commercial app plans."},
 {name:"Central Athlete EVL",fit:"Best short-form licensed demo lead",note:"2,800+ exercise demos averaging under 20 seconds; strong candidate for replacing YouTube-style media after licensing."},
 {name:"wger",fit:"Useful open/direct supplement",note:"Direct video files exist, but current public coverage is sparse for no-equipment calisthenics."},
 {name:"Studio capture",fit:"Best long-term Bodywise identity",note:"Shoot 15–25 second vertical clips for exact variations that libraries do not cover cleanly."}
];
const candidateSourcePass=[
 {move:"Wall push-up",source:"FAME / Pexels / IFPE",status:"Exact real-human candidates found; do not publish until usage rights and no-intro clip start are verified."},
 {move:"Counter or chair push-up",source:"FAME Chair Pushups",status:"Exact beginner push variation found; held for licensing review instead of being reused silently."},
 {move:"Sit-to-stand",source:"FAME + clinic rehab libraries",status:"Exact real-human candidates found; useful for knee-strength track after rights check."},
 {move:"High-knee march / ankle rotations",source:"FAME",status:"Exact mobility clips found; held because FAME materials carry UBC program terms."},
 {move:"Dead bug / bird dog / side plank",source:"Lyndhurst / physio libraries",status:"Exact rehab-style candidates found; clinic-use wording means app rights still need confirmation."},
 {move:"Rejected source",source:"free-exercise-db-with-videos",status:"Not added: despite real-video wording, provenance points to an animated exercise set, which fails the real-people-only rule."}
];
type MuscleWikiCandidate={id:number;name:string;difficulty?:string|null;category?:string|null;muscles:string[];videoCount:number;videos:{index:number;gender?:string;angle?:string;type?:string;filename?:string;path?:string;hasStream:boolean}[]};
const muscleWikiReviewQueue=[
 {bodywise:"Forearm plank",query:"forearm plank",rule:"Must show elbows under shoulders in a static plank hold.",status:"Searchable through MuscleWiki; approve only exact forearm plank, not push-up plank."},
 {bodywise:"Knee plank",query:"knee plank",rule:"Knees down, straight shoulder-hip-knee line, no crunch or cobra transition.",status:"Needs exact candidate review before replacing placeholder."},
 {bodywise:"Incline push-up",query:"incline push up",rule:"Hands elevated on bench/counter, full-body line, visible lowering and press.",status:"Search first; use stock/studio if MuscleWiki result is flat push-up only."},
 {bodywise:"Sit-to-stand",query:"sit to stand",rule:"User starts seated, stands fully, and sits/taps chair again.",status:"High priority for knee-strength track."},
 {bodywise:"Marching bridge",query:"marching glute bridge",rule:"Bridge position with alternating knee lift and level hips.",status:"Do not map ordinary glute bridge unless the march is visible."},
 {bodywise:"Bear crawl hold",query:"bear crawl hold",rule:"Quadruped hover with knees off floor; no crawling travel required.",status:"Approve only if the hover is clearly shown."},
 {bodywise:"Tucked hollow hold",query:"tuck hollow body hold",rule:"Supine hollow shape with knees tucked and low-back control.",status:"Likely needs studio capture if MuscleWiki has only full hollow hold."},
 {bodywise:"Crow-prep balance",query:"crow pose",rule:"Real person balance/crow prep, not an illustration or yoga title card.",status:"Can use exact crow pose as a skill milestone after review."}
];
const approvedMuscleWikiMappings=[
 {move:"Dead bug",source:"Local/open-access clip",status:"Approved in app"},
 {move:"Bird dog",source:"Local/open-access clip",status:"Approved in app"},
 {move:"Side plank",source:"Local/open-access clip",status:"Approved in app"},
 {move:"Bodyweight squat",source:"Bodywise direct loop",status:"Approved in app"},
 {move:"MuscleWiki stream",source:"Private API connector",status:"Ready after MuscleWiki plan upgrade"}
];
type ShortLoopClip={move:string;source:string;url:string;loop:string;status:string;preview?:string;poster?:string;ready?:boolean;media?:"video"|"image"};
const shortLoopCollection:ShortLoopClip[]=[
 {move:"Bodyweight squat",source:"Bodywise local verified clip",url:"/squat-loop.mp4",preview:"/squat-loop.mp4",poster:"/squat-real.jpg",loop:"4–6 sec loop · full squat rep",status:"Approved local Bodywise real-person loop.",ready:true,media:"video"},
 {move:"Glute bridge",source:"Bodywise local verified clip",url:"/bridge-loop.mp4",preview:"/bridge-loop.mp4",poster:"/bridge-real.jpg",loop:"4–6 sec loop · one full lift and lower",status:"Approved local Bodywise bridge loop.",ready:true,media:"video"},
 {move:"Dead bug",source:"Bodywise local open-access clip",url:"/dead-bug-real.mp4",preview:"/dead-bug-real.mp4",poster:"/dead-bug-real.jpg",loop:"4–6 sec loop · controlled opposite reach",status:"Approved local Bodywise core-control loop.",ready:true,media:"video"},
 {move:"Bird dog",source:"Bodywise local open-access clip",url:"/bird-dog-real.mp4",preview:"/bird-dog-real.mp4",poster:"/bird-dog-real.jpg",loop:"4–6 sec loop · opposite arm/leg reach",status:"Approved local Bodywise trunk-stability loop.",ready:true,media:"video"},
 {move:"Side plank",source:"Bodywise local open-access clip",url:"/side-plank-real.mp4",preview:"/side-plank-real.mp4",poster:"/side-plank-real.jpg",loop:"3–5 sec hold loop",status:"Approved local Bodywise side-core loop.",ready:true,media:"video"},
 {move:"Wall push-up",source:"Bodywise Original Demo",url:"/bodywise-wall-pushup-demo.mp4",preview:"/bodywise-wall-pushup-demo.mp4",poster:"/pushup-real.jpg",loop:"4 sec loop · wall press and return",status:"Owned app demo: no third-party licensing dependency.",ready:true,media:"video"},
 {move:"Marching bridge",source:"Bodywise Original Demo",url:"/bodywise-marching-bridge-demo.mp4",preview:"/bodywise-marching-bridge-demo.mp4",poster:"/bridge-real.jpg",loop:"4 sec loop · bridge march with level hips",status:"Owned app demo: replaces external glute bridge alternate preview.",ready:true,media:"video"},
 {move:"Plank shoulder taps",source:"Bodywise Original Demo",url:"/bodywise-plank-shoulder-taps-demo.mp4",preview:"/bodywise-plank-shoulder-taps-demo.mp4",poster:"/plank-real.jpg",loop:"4 sec loop · alternating shoulder taps",status:"Owned app demo: no third-party licensing dependency.",ready:true,media:"video"},
 {move:"Chair tap squat",source:"Bodywise Original Demo",url:"/bodywise-chair-tap-squat-demo.mp4",preview:"/bodywise-chair-tap-squat-demo.mp4",poster:"/squat-real.jpg",loop:"4 sec loop · chair tap to stand",status:"Owned app demo: replaces Tenor preview.",ready:true,media:"video"},
 {move:"Sit-to-stand",source:"Bodywise Original Demo",url:"/bodywise-sit-to-stand-demo.mp4",preview:"/bodywise-sit-to-stand-demo.mp4",poster:"/squat-real.jpg",loop:"4 sec loop · seated to fully standing",status:"Owned app demo: no third-party licensing dependency.",ready:true,media:"video"},
 {move:"Tucked hollow hold",source:"Bodywise Original Demo",url:"/bodywise-tucked-hollow-demo.mp4",preview:"/bodywise-tucked-hollow-demo.mp4",poster:"/dead-bug-real.jpg",loop:"4 sec hold loop · tucked hollow shape",status:"Owned app demo: solves the missing tucked hollow visual.",ready:true,media:"video"},
 {move:"Bear crawl hold",source:"Bodywise Original Demo",url:"/bodywise-bear-hold-demo.mp4",preview:"/bodywise-bear-hold-demo.mp4",poster:"/bird-dog-real.jpg",loop:"4 sec hover hold",status:"Owned app demo: no third-party licensing dependency.",ready:true,media:"video"}
];const exactPreviewByMoveName=new Map(shortLoopCollection.filter(x=>x.preview).map(x=>[x.move,x]));
const movePreviewAliases:Record<string,string>={
 "Wall push-up":"Wall push-up",
 "Sit-to-stand":"Sit-to-stand",
 "Marching bridge":"Marching bridge",
 "Plank shoulder tap prep":"Plank shoulder taps",
 "Bear crawl hold":"Bear crawl hold"
};
const exactMoveMediaNames=new Set(["Bodyweight squat","Glute bridge","Wall push-up","Sit-to-stand","Marching bridge","Plank shoulder tap prep","Bear crawl hold","Standing calf raise","Dead bug","Forearm plank","Bird dog","Side plank"]);
function sourcingPlan(name:string){const n=name.toLowerCase();
 if(n.includes("push"))return{lead:"Push variation lead",query:`exact real human ${name} exercise demo commercial license mp4 no animation no YouTube`,provider:"YMove API, Pexels licensed stock, IFPE/FAME only after written rights confirmation",url:"https://ymove.app/exercise-api",route:"License a matching clip, then trim to the first clean rep and save as a Bodywise loop."};
 if(n.includes("squat")||n.includes("stand")||n.includes("knee"))return{lead:"Knee + squat lead",query:`exact real human ${name} exercise demo sit stand squat commercial license mp4`,provider:"YMove, Central Athlete EVL, FAME/clinic clips after written app-use permission",url:"https://www.centralathlete.com/exercise-video-library",route:"Prioritize frontal/side view, knee tracking visible, no chair reuse unless the move is actually chair-based."};
 if(n.includes("plank")||n.includes("dead bug")||n.includes("bird")||n.includes("heel")||n.includes("bear"))return{lead:"Core control lead",query:`exact real human ${name} rehab core exercise demo licensed mp4 no animation`,provider:"MuscleWiki API, YMove, physio libraries only with confirmed redistribution rights",url:"https://api.musclewiki.com/",route:"Verify the named position, crop away introductions, and loop 2-3 clean reps or one stable hold."};
 if(n.includes("bridge")||n.includes("calf")||n.includes("ankle")||n.includes("march"))return{lead:"Lower-body support lead",query:`exact real human ${name} exercise demo licensed mp4 real person`,provider:"YMove, Central Athlete EVL, wger when exact, or Bodywise studio capture",url:"https://ymove.app/exercise-video-library",route:"Use only clips where the lower-body action is unmistakable and starts directly at movement."};
 return{lead:"Exact movement lead",query:`exact real human ${name} calisthenics exercise demo commercial license mp4`,provider:"YMove / MuscleWiki / Kinetic.place / Bodywise studio capture",url:"https://kinetic.place/",route:"If no source passes, shoot a 15-25 second Bodywise clip instead of substituting a lookalike."}}
function ExactClipNeeded({name,large=false}:{name:string;large?:boolean}){const s=sourcingPlan(name);return <div className={"movement-media media-needed "+(large?"large":"")}><div><b>Secure exact clip</b><p>No lookalike video is shown for {name}. Next action: identify, verify, license or shoot the exact real-person movement.</p><ul className="media-actions"><li><span>Search phrase</span><em>{s.query}</em></li><li><span>Best source route</span><em>{s.provider}</em></li><li><span>Approval rule</span><em>Named move must match, real human only, no intro/title card, rights cleared for app use.</em></li><li><span>Production fallback</span><em>{s.route}</em></li></ul><a className="source-link" href={s.url} target="_blank" rel="noreferrer">Open {s.lead}</a></div></div>}
function hasVaultDemo(item:(typeof vault)[number],move:Move){return Boolean(vaultExactVideos[item.name]||exactPreviewByMoveName.get(movePreviewAliases[move.name]||move.name)||exactMoveMediaNames.has(move.name))}
function VaultMedia({item,move}:{item:(typeof vault)[number];move:Move}){const v=vaultExactVideos[item.name]||exactPreviewByMoveName.get(movePreviewAliases[move.name]||move.name);if(v)return <div className="movement-media large vault-direct" data-source="bodywise-demo"><video src={(v as any).src||(v as ShortLoopClip).preview} poster={(v as any).poster||move.image} autoPlay loop muted playsInline preload="auto" aria-label={item.name+" Bodywise movement demo"}/><div className="media-shade"/><span className="media-credit">{(v as any).credit||(v as ShortLoopClip).source}</span><span className="loop-badge">↻ BODYWISE DEMO</span></div>;if(exactMoveMediaNames.has(move.name))return <div className="movement-media large vault-direct"><video src={move.video} poster={move.image} autoPlay loop muted playsInline preload="auto" aria-label={item.name+" movement demonstration"}/><div className="media-shade"/>{move.credit&&<span className="media-credit">{move.credit}</span>}<span className="loop-badge">↻ MOVE DEMO</span></div>;return <ExactClipNeeded name={item.name} large/>}
function ClipCard({x}:{x:ShortLoopClip}){return <article className={x.ready?"ready":"candidate"} key={x.move+x.source}>{x.preview?<div className="clip-preview">{x.media==="image"?<img src={x.preview} alt={x.move+" short Bodywise movement demo"}/>:<video src={x.preview} poster={x.poster} muted loop autoPlay playsInline preload="metadata" aria-label={x.move+" short Bodywise loop demo"}/>}<b>{x.ready?"APPROVED":"VIEWABLE"}</b></div>:<a className="clip-link-preview" href={x.url} target="_blank" rel="noreferrer"><span>OPEN SOURCE</span><b>{x.move}</b></a>}<div className="clip-copy"><small>{x.ready?"APPROVED LOOP":"VIEWABLE EXACT PREVIEW"}</small><h3>{x.move}</h3><p>{x.loop}</p><em>{x.status}</em><a href={x.url} target="_blank" rel="noreferrer">Review source →</a></div></article>}function ClipCollectionBoard(){const ready=shortLoopCollection.filter(x=>x.ready),queued=shortLoopCollection.filter(x=>!x.ready);return <section className="clip-collection-board"><div className="clip-collection-head"><div><p className="eyebrow">CLIP COLLECTION</p><h2>Bodywise-owned movement demos</h2><p>Every card below shows the named movement from a local Bodywise asset, so the app no longer depends on borrowed third-party preview clips.</p></div><span>{ready.length} APPROVED · {queued.length} PREVIEWS</span></div><div className="clip-subhead"><b>Owned loops</b><small>Playable local Bodywise assets</small></div><div className="clip-grid ready-grid">{ready.map(x=><ClipCard x={x} key={x.move+x.source}/>)}</div><div className="clip-subhead queued"><b>Ready in app</b><small>No external clip dependency</small></div><div className="clip-grid queued-grid">{queued.map(x=><ClipCard x={x} key={x.move+x.source}/>)}</div></section>}function MuscleWikiMappingBoard(){
 const[selected,setSelected]=useState(muscleWikiReviewQueue[0]),[results,setResults]=useState<MuscleWikiCandidate[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 async function search(item=selected){setSelected(item);setLoading(true);setError("");setResults([]);try{const res=await fetch("/api/musclewiki/search?q="+encodeURIComponent(item.query));const data=await res.json();if(!res.ok){setError(data.upgradeUrl?data.error+" Upgrade direct API access to activate live search.":data.error||"MuscleWiki search failed.");return}setResults(data.results||[])}catch{setError("Could not reach the Bodywise MuscleWiki connector.")}finally{setLoading(false)}}
 return <section className="musclewiki-board"><div className="mw-head"><div><p className="eyebrow">MUSCLEWIKI CONNECTOR</p><h2>Search, approve, then stream</h2><p>Bodywise now routes MuscleWiki through a private backend. A clip is mapped only after the movement name, real-human footage and starting frame pass review.</p></div><button onClick={()=>search()}>{loading?"Searching…":"Search selected"}</button></div><div className="mw-approved">{approvedMuscleWikiMappings.map(x=><article key={x.move}><b>{x.move}</b><span>{x.source}</span><p>{x.status}</p></article>)}</div><div className="mw-workbench"><div className="mw-queue">{muscleWikiReviewQueue.map(item=><button key={item.bodywise} className={selected.bodywise===item.bodywise?"selected":""} onClick={()=>search(item)}><b>{item.bodywise}</b><span>{item.query}</span><small>{item.status}</small></button>)}</div><div className="mw-results"><h3>{selected.bodywise}</h3><p><b>Approval rule:</b> {selected.rule}</p>{error&&<div className="mw-error">{error}</div>}{!error&&!loading&&results.length===0&&<div className="mw-empty">Tap Search selected to pull candidates. Basic MuscleWiki keys may show an upgrade notice here.</div>}{loading&&<div className="mw-empty">Searching MuscleWiki through the Bodywise connector…</div>}{results.map(r=><article key={r.id}><div><b>{r.name}</b><span>{r.category||"Bodyweight"} · {r.difficulty||"difficulty unknown"}</span><small>{r.muscles.join(" · ")||"Muscles not listed"}</small></div><em>{r.videoCount} video option{r.videoCount===1?"":"s"}</em><p>{r.name.toLowerCase()===selected.bodywise.toLowerCase()?"Name match — still verify the actual movement before approval.":"Review required — do not auto-map unless the clip exactly matches Bodywise’s named move."}</p></article>)}</div></div></section>
}
function workTime(base:number,age:string,level:Level,readiness:Readiness){const a:Record<string,number>={"13–17":.9,"18–29":1,"30–44":1,"45–59":.9,"60+":.78},l:Record<Level,number>={Beginner:.82,Intermediate:1,Advanced:1.18},r:Record<Readiness,number>={Recover:.72,Ready:1,Push:1.12};return Math.max(20,Math.round(base*a[age]*l[level]*r[readiness]/5)*5)}
function MovementMedia({move,large=false}:{move:Move;large?:boolean}){const preview=exactPreviewByMoveName.get(movePreviewAliases[move.name]||move.name);if(preview)return <div className={"movement-media "+(large?"large":"")} data-source="bodywise-demo">{preview.media==="image"?<img src={preview.preview} alt={move.name+" exact Bodywise movement demo"}/>:<video src={preview.preview} poster={preview.poster||move.image} autoPlay loop muted playsInline preload={large?"auto":"metadata"} aria-label={move.name+" exact Bodywise movement demo"}/>}<div className="media-shade"/><span className="media-credit">{preview.source}</span><span className="loop-badge">↻ BODYWISE DEMO</span></div>;if(!exactMoveMediaNames.has(move.name))return <ExactClipNeeded name={move.name} large={large}/>;return <div className={"movement-media "+(large?"large":"")}><video src={move.video} poster={move.image} autoPlay loop muted playsInline preload={large?"auto":"metadata"} aria-label={move.name+" exact real-person movement demonstration"}/><div className="media-shade"/>{move.credit&&<span className="media-credit">{move.credit}</span>}<span className="loop-badge">↻ EXACT VIDEO</span></div>}
export default function Home(){
 const[goal,setGoal]=useState<Goal>("Full body"),[age,setAge]=useState("30–44"),[sex,setSex]=useState<Sex>("Prefer not to say"),[level,setLevel]=useState<Level>("Beginner"),[readiness,setReadiness]=useState<Readiness>("Ready");
 const[profile,setProfile]=useState(false),[adapt,setAdapt]=useState(false),[session,setSession]=useState(false),[finish,setFinish]=useState(false),[showWhy,setShowWhy]=useState(false),[vaultMove,setVaultMove]=useState<(typeof vault)[number]|null>(null),[running,setRunning]=useState(false),[active,setActive]=useState(0),[left,setLeft]=useState(0),[tab,setTab]=useState<Tab>("Today"),[targetMinutes,setTargetMinutes]=useState(20),[quiet,setQuiet]=useState(false),[caption,setCaption]=useState(true),[audioHints,setAudioHints]=useState(true),[kudos,setKudos]=useState(18),[rotation,setRotation]=useState(0);
 const goalData=goals[goal],keys=goalData.rotations[rotation%goalData.rotations.length],plan=useMemo(()=>keys.map((k,i)=>({...M[k],seconds:workTime(M[k].base+(i%2?5:0),age,level,readiness)})),[keys,age,level,readiness]),minutes=targetMinutes,current=plan[active]||plan[0],freshness=Math.min(96,62+rotation*7+Object.keys(goals).indexOf(goal)*2);
 useEffect(()=>{const raw=localStorage.getItem("bodywise-profile");if(raw){try{const p=JSON.parse(raw);if(p.goal&&goals[p.goal as Goal])setGoal(p.goal);if(p.age)setAge(p.age);if(p.sex)setSex(p.sex);if(p.level)setLevel(p.level)}catch{}}},[]);
 useEffect(()=>{if(!running||left<=0)return;const t=window.setInterval(()=>setLeft(v=>v-1),1000);return()=>clearInterval(t)},[running,left]); useEffect(()=>{if(session)setLeft(current.seconds)},[active,current.seconds,session]);
 function chooseGoal(next:Goal){setGoal(next);setActive(0);setSession(false);setRunning(false);setRotation(0)} function saveProfile(){localStorage.setItem("bodywise-profile",JSON.stringify({goal,age,sex,level}));setProfile(false)} function start(){setActive(0);setLeft(plan[0].seconds);setRunning(true);setFinish(false);setSession(true)} function next(){if(active===plan.length-1){setSession(false);setRunning(false);setFinish(true)}else{setActive(v=>v+1);setRunning(true)}}
 return <main className="app-shell">
  <header className="topbar premium-topbar"><button className="brand" onClick={()=>setTab("Today")} aria-label="Bodywise home"><b>B</b>BODYWISE</button><div className="top-actions"><span className="streak-pill">⚡ {freshness}% FRESH</span><button className="profile-pill" onClick={()=>setProfile(true)} aria-label="Open training profile"><span>{age}</span><b>{sex==="Female"?"F":sex==="Male"?"M":"·"}</b></button></div></header>
  {tab==="Today"&&<><section className="intro home-hero"><div className="hero-date"><p className="eyebrow">ROTATION {rotation+1} · WEEK 2</p><span>{goal.toUpperCase()}</span></div><h1>Never the<br/><em>same.</em></h1><p>Choose a target, spin a fresh bodyweight session, and follow exact matching movement clips only — no borrowed or lookalike videos.</p><div className="hero-proof"><span><b>{vault.length}</b> variations mapped</span><span><b>{plan.length}</b> moves today</span></div></section>
  <section className="coach-note"><div className="coach-avatar">K</div><div><small>COACH KAI · VARIETY ENGINE</small><b>{goalData.promise}</b><p>Each target has multiple rotations so users keep seeing new sessions without losing progression.</p></div></section>
  <ClipCollectionBoard/>
  <section className="readiness-row"><div><p className="eyebrow">HOW DO YOU FEEL?</p><h2>Set today’s pace</h2></div><div>{(["Recover","Ready","Push"] as Readiness[]).map(x=><button key={x} className={readiness===x?"selected":""} onClick={()=>setReadiness(x)}>{x}</button>)}</div></section>
  <section className="target-section"><div className="target-heading"><div><p className="eyebrow">SELECT A TARGET</p><h2>What are we building?</h2></div><b>{Object.keys(goals).length} GOALS</b></div><div className="target-grid">{(Object.keys(goals) as Goal[]).map(name=><button className={goal===name?"selected":""} onClick={()=>chooseGoal(name)} key={name}><i>{goals[name].icon}</i><span>{name}</span><small>{goals[name].desc}</small>{goal===name&&<b>✓</b>}</button>)}</div>{goal==="Knee strength"&&<p className="knee-note">Knee work should feel controlled, not painful. If pain persists, ask a qualified clinician.</p>}</section>
  <section className="variety-card"><div><p className="eyebrow">ANTI-BOREDOM MODE</p><h2>Spin a fresh session</h2><p>Same target, different order, different emphasis, with exact-video discipline.</p></div><button onClick={()=>{setRotation(v=>(v+1)%3);setActive(0)}}>Shuffle today ↻</button><div className="fresh-meter"><i style={{width:freshness+"%"}}/><span>{freshness}% freshness</span></div></section>
  <section className="workout featured-workout"><img src={plan[0].image} alt={goal+" workout"}/><div className="shade"/><div className="workout-copy"><span className="tag">TODAY’S RECOMMENDATION</span><div className="coach-byline"><i>K</i><span>Coach Kai · {readiness} pace · Rotation {rotation+1}</span></div><h2>{goalData.title}</h2><p>{quiet?"Quiet mode is on: no jumping and apartment-friendly movement.":goalData.desc}</p><div className="stats"><span><b>{minutes}</b> min</span><span><b>{plan.length}</b> moves</span><span><b>3</b> rounds</span></div></div><button className="start" onClick={start}>Start today’s workout <b>→</b></button></section>
  <button className="adapt-today" onClick={()=>setAdapt(true)}><span>⚙</span><div><b>Adapt today</b><small>Change time, space or intensity</small></div><i>→</i></button>
  <section className="packs"><p className="eyebrow">MOVEMENT FAMILIES</p><h2>More variety, less randomness</h2><div>{plan.map(x=><article key={x.name}><MovementMedia move={x}/><div><small>{x.family} · {x.intensity}</small><h3>{x.name}</h3><p>{x.why}</p><div>{x.variants.map(v=><span key={v}>{v}</span>)}</div></div></article>)}</div></section>
  <section className="recovery-card"><div><p className="eyebrow">ESTIMATED RECOVERY</p><h2>Your body map</h2><small>Based on recent sessions—not a medical measurement.</small></div><div className="recovery-bars"><span><i style={{width:"82%"}}/>Core <b>82%</b></span><span><i style={{width:"64%"}}/>Upper <b>64%</b></span><span><i style={{width:"91%"}}/>Lower <b>91%</b></span></div><button className="why-button" onClick={()=>setShowWhy(v=>!v)} aria-expanded={showWhy}>{showWhy?"Hide":"Why this workout?"}<b>{showWhy?"−":"+"}</b></button>{showWhy&&<div className="why-copy"><b>Why Bodywise chose this</b><p>This rotation matches your {goal} target, {readiness} pace, age range and current time window. No convenience reuse is allowed: exact matching clips display, and missing exact clips are clearly marked for licensing or studio capture.</p></div>}</section>
  <section className="vault-card"><div><p className="eyebrow">MOVE VAULT</p><h2>{vault.length} ways to keep growing</h2><p>Tap any move for exact media status, cues and progression context.</p></div><div>{vault.map(v=><button key={v.name} onClick={()=>setVaultMove(v)}><span>{v.name}</span><small>{M[v.move].family}</small></button>)}</div></section><section className="source-pass-card"><div><p className="eyebrow">VIDEO SOURCE PASS</p><h2>Exact clips only</h2><p>Bodywise now shows only exact matching clips. If a movement still needs licensed or studio-shot media, the app says so instead of borrowing a related video.</p></div><div>{premiumSourcePlan.map(x=><article key={x.name}><b>{x.name}</b><span>{x.fit}</span><p>{x.note}</p></article>)}</div><div className="candidate-source-list"><h3>Candidate clips under review</h3>{candidateSourcePass.map(x=><article key={x.move}><b>{x.move}</b><span>{x.source}</span><p>{x.status}</p></article>)}</div></section>
  <MuscleWikiMappingBoard/>
  <section className="section-head"><div><p className="eyebrow">YOUR TARGETED PLAN</p><h2>{goal} movements</h2></div><span>{plan.length} selected</span></section><section className="exercise-list">{plan.map((x,i)=><article className="exercise" key={x.name}><div className="exercise-image"><MovementMedia move={x}/></div><div className="exercise-copy"><small>0{i+1} · {x.focus}</small><h3>{x.name}</h3><p>{x.cue}</p><span>If an exact clip is available, match its pace; otherwise follow the written cues until the correct clip is sourced.</span></div><aside><b>{x.seconds}</b><small>SEC</small></aside></article>)}</section></>}
  {tab==="Plan"&&<PlanPage goal={goal} minutes={minutes}/>} {tab==="Community"&&<CommunityPage kudos={kudos} onKudos={()=>setKudos(v=>v+1)}/>} {tab==="Progress"&&<ProgressPage goal={goal}/>} 
  <nav className="bottom-nav provider-nav">{nav.map((x,i)=><button className={tab===x?"selected":""} onClick={()=>setTab(x)} key={x}><span>{["●","▤","◎","◔"][i]}</span>{x}</button>)}</nav>
  {adapt&&<div className="overlay" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setAdapt(false)} aria-label="Close"/><section className="sheet adapt-sheet"><i/><button className="close" onClick={()=>setAdapt(false)}>×</button><p className="eyebrow">FREE UP THE PLAN</p><h2>Adapt today.</h2><fieldset><legend>Time available</legend><div className="choices">{[10,15,20].map(x=><button className={targetMinutes===x?"chosen":""} onClick={()=>setTargetMinutes(x)} key={x}>{x} min</button>)}</div></fieldset><fieldset><legend>Energy</legend><div className="choices">{(["Recover","Ready","Push"] as Readiness[]).map(x=><button className={readiness===x?"chosen":""} onClick={()=>setReadiness(x)} key={x}>{x}</button>)}</div></fieldset><label className="quiet-toggle"><span><b>Quiet mode</b><small>No jumping · small-space friendly</small></span><input type="checkbox" checked={quiet} onChange={e=>setQuiet(e.target.checked)}/></label><button className="save" onClick={()=>setAdapt(false)}>Update today’s workout</button></section></div>}
  {vaultMove&&<div className="overlay" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setVaultMove(null)} aria-label="Close"/><section className="sheet vault-sheet"><i/><button className="close" onClick={()=>setVaultMove(null)}>×</button><p className="eyebrow">MOVE VAULT GUIDE</p><h2>{vaultMove.name}</h2><div className="vault-visual"><VaultMedia item={vaultMove} move={M[vaultMove.move]}/></div><div className="vault-guide-copy"><small>{M[vaultMove.move].family} · {M[vaultMove.move].intensity}</small><h3>{M[vaultMove.move].cue}</h3><p>{M[vaultMove.move].detail}</p><b>Why it matters</b><p>{M[vaultMove.move].why}</p><b>Progressions</b><div>{M[vaultMove.move].variants.map(x=><span key={x}>{x}</span>)}</div><em>{hasVaultDemo(vaultMove,M[vaultMove.move])?"Bodywise demo: local clip shown inside the Move Vault.":"No borrowed placeholder is shown; add a Bodywise-owned demo before publishing this move as complete."}</em></div><button className="save" onClick={()=>{setVaultMove(null);setGoal("Skill Prep");setTab("Today")}}>Train related moves</button></section></div>}
  {profile&&<div className="overlay" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setProfile(false)} aria-label="Close"/><section className="sheet"><i/><button className="close" onClick={()=>setProfile(false)}>×</button><p className="eyebrow">PERSONALISE YOUR START</p><h2>Make the plan yours.</h2><p className="note">Age and experience tune the starting pace. Sex is optional health context and does not change your workout.</p><fieldset><legend>Training target</legend><div className="choices target-choices">{(Object.keys(goals) as Goal[]).map(x=><button className={goal===x?"chosen":""} onClick={()=>chooseGoal(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Age range</legend><div className="choices ages">{ages.map(x=><button className={age===x?"chosen":""} onClick={()=>setAge(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Sex · optional health context</legend><div className="choices">{(["Female","Male","Prefer not to say"] as Sex[]).map(x=><button className={sex===x?"chosen":""} onClick={()=>setSex(x)} key={x}>{x}</button>)}</div></fieldset><fieldset><legend>Experience</legend><div className="choices">{(["Beginner","Intermediate","Advanced"] as Level[]).map(x=><button className={level===x?"chosen":""} onClick={()=>setLevel(x)} key={x}>{x}</button>)}</div></fieldset><div className="preview"><span>{goal} practice</span><b>{minutes} min · {plan.length} targeted movements · {vault.length} vault variations</b></div><button className="save" onClick={saveProfile}>Save my plan</button></section></div>}
  {session&&<section className="session premium-session" role="dialog" aria-modal="true"><header><button onClick={()=>{setSession(false);setRunning(false)}}>×</button><span>{goal.toUpperCase()} · MOVE {active+1} OF {plan.length}</span><button>◒</button></header><div className="live-metrics"><span><small>HEART RATE · DEMO</small><b>124 <i>BPM</i></b></span><span><small>EFFORT · DEMO</small><b>6 <i>/10</i></b></span><span><small>ACTIVE · DEMO</small><b>38 <i>KCAL</i></b></span></div><div className="session-title"><p>{current.family}</p><h2>{current.name}</h2></div><div className="session-visual"><MovementMedia move={current} large/></div><div className="session-tools"><button className={audioHints?"on":""} onClick={()=>setAudioHints(v=>!v)}>◖ Audio hints</button><button className={caption?"on":""} onClick={()=>setCaption(v=>!v)}>CC Captions</button><button onClick={()=>setRotation(v=>(v+1)%3)}>◐ Swap</button><button>♫ Focus mix</button></div>{caption&&<p className="caption">{current.detail}</p>}<div className="cue"><span>COACH KAI</span><b>{current.cue}</b><p>{audioHints?"Audio hint on · ":""}{current.detail}</p></div><div className="timer-row"><div className="timer" style={{background:"conic-gradient(#e8ff48 "+((current.seconds-left)/current.seconds*100)+"%,#2e302a 0)"}}><div><b>{left}</b><span>SECONDS</span></div></div><button onClick={()=>setRunning(v=>!v)}>{running?"Ⅱ":"▶"}<span>{running?"Pause":"Resume"}</span></button><button className="next" onClick={next}>→<span>{active===plan.length-1?"Finish":"Next"}</span></button></div><div className="session-progress"><i style={{width:((active+1)/plan.length*100)+"%"}}/></div></section>}
  {finish&&<div className="overlay finish" role="dialog" aria-modal="true"><button className="backdrop" onClick={()=>setFinish(false)} aria-label="Close"/><section className="finish-card"><span>✓</span><p className="eyebrow">SESSION COMPLETE</p><h2>Strong work.</h2><p>You kept the promise you made to yourself today. Next time, spin a new rotation to keep it fresh.</p><div className="summary-metrics"><b>{minutes}<small>MIN</small></b><b>{plan.length}<small>MOVES</small></b><b>+1<small>STREAK</small></b></div><div className="rating"><small>HOW DID THAT FEEL?</small><div>{["Too easy","Just right","Too hard"].map(x=><button key={x}>{x}</button>)}</div></div><button className="share-result" onClick={()=>setRotation(v=>(v+1)%3)}>Unlock next variation</button><button className="done" onClick={()=>setFinish(false)}>Done</button></section></div>}
 </main>}
function PlanPage({goal,minutes}:{goal:Goal;minutes:number}){const days=[{d:"MON",n:"14",s:"DONE",t:"Foundation"},{d:"TUE",n:"15",s:"REST",t:"Mobility"},{d:"WED",n:"16",s:"TODAY",t:goal},{d:"FRI",n:"18",s:"UP NEXT",t:"Fresh rotation"},{d:"SUN",n:"20",s:"OPTIONAL",t:"Skill prep"}];return <section className="platform-page plan-page"><p className="eyebrow">YOUR CUSTOM PLAN</p><h1>Stay<br/><em>curious.</em></h1><p className="page-lede">A flexible week that rotates movement families so users get novelty without losing structure.</p><div className="plan-summary"><span><b>3</b> days / week</span><span><b>{minutes}</b> min / session</span><span><b>{Object.keys(goals).length}</b> goal packs</span></div><div className="week-plan">{days.map(x=><article className={x.s==="TODAY"?"today":""} key={x.d}><div><small>{x.d}</small><b>{x.n}</b></div><span>{x.s}</span><h3>{x.t}</h3><p>{x.s==="REST"?"Breathe · stretch · walk":minutes+" min · Coach Kai"}</p>{x.s==="TODAY"&&<button>Start →</button>}</article>)}</div><div className="plan-controls"><h2>Plan upgrades</h2><button><span>Rotation logic</span><b>3 versions per goal →</b></button><button><span>Boredom guard</span><b>Shuffle + vault →</b></button><button><span>Media promise</span><b>Exact clips only →</b></button></div><div className="coach-program"><span>COACH KAI · BLOCK 1</span><h2>Own the basics, then vary them.</h2><p>The app now teaches families, progressions and swaps — the part that keeps people from quitting after week one.</p><i>WEEK 2 OF 4</i></div></section>}
function CommunityPage({kudos,onKudos}:{kudos:number;onKudos:()=>void}){return <section className="platform-page community-page"><p className="eyebrow">BODYWISE CLUB</p><h1>Better<br/><em>together.</em></h1><p className="page-lede">A supportive, opt-in space for showing up — with weekly variety challenges.</p><article className="challenge"><span>THIS WEEK’S CHALLENGE</span><h2>Try 3 different rotations.</h2><div><i style={{width:"58%"}}/></div><p><b>7</b> of 12 sessions · 13 days left</p><button>View challenge →</button></article><div className="club-strip"><span><b>2,418</b> members</span><span><b>386</b> trained today</span><span><b>94%</b> supportive</span></div><div className="feed"><h2>Club feed</h2><article><div className="member">AR</div><div><b>Amara R.</b><small>2 HOURS AGO · CORE CONTROL</small><p>The side plank rotation finally made core day feel different.</p><button onClick={onKudos}>▲ {kudos} kudos</button><button>Reply</button></div></article><article><div className="member rust">JL</div><div><b>Jon L.</b><small>YESTERDAY · QUIET SWEAT</small><p>Quiet conditioning in a hotel room. Zero jumping, still sweaty.</p><button>▲ 24 kudos</button><button>Reply</button></div></article></div><p className="privacy-note">Community sharing is opt-in. Your age, sex and health context stay private.</p></section>}
function ProgressPage({goal}:{goal:Goal}){return <section className="platform-page progress-page"><p className="eyebrow">YOUR PROGRESS</p><h1>Proof of<br/><em>practice.</em></h1><p className="page-lede">Track consistency, capacity, movement variety and the skills you are earning.</p><div className="score-grid"><article><span>THIS WEEK</span><b>3<small>/3</small></b><p>sessions complete</p></article><article><span>VARIETY SCORE</span><b>84<small>%</small></b><p>new movement exposure</p></article><article><span>TRAINING TIME</span><b>62<small> MIN</small></b><p>+14% vs last week</p></article><article><span>FOCUS</span><b className="focus-score">{goal}</b><p>current block</p></article></div><article className="load-chart"><div><span>TRAINING LOAD</span><b>Balanced</b></div><div className="bars">{[42,61,36,78,58,90,70].map((x,i)=><i key={i} style={{height:x+"%"}}/>)}</div>{["MON","TUE","WED","THU","FRI","SAT","SUN"].map(x=><small key={x}>{x}</small>)}</article><article className="skill-path"><span>SKILL PATH · PUSH-UP</span><h2>Build it one step at a time.</h2>{["Wall push-up","Incline push-up","Slow negative","Full push-up"].map((x,i)=><div className={i<2?"done":i===2?"current":""} key={x}><i>{i<2?"✓":i+1}</i><span><b>{x}</b><small>{i<2?"Mastered":i===2?"In progress · 68%":"Locked"}</small></span></div>)}</article><article className="latest-win"><span>YOUR LATEST WIN</span><h2>Unlocked rotation variety</h2><p>More choices, same bodyweight foundation, Bodywise-owned media preferred.</p><button>Share achievement →</button></article></section>}














